# Copyright 2016 CampaignChain, Inc. <info@campaignchain.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
    campaignchain.campaign.template.hook:
        class: CampaignChain\Campaign\TemplateBundle\EntityService\HookService
        arguments: [ @doctrine, @service_container ]
    campaignchain.campaign.template.copy:
        class: CampaignChain\Campaign\TemplateBundle\EntityService\CopyService
        arguments: [ @doctrine, @service_container ]
    campaignchain.validator.campaign.template:
        class: CampaignChain\Campaign\TemplateBundle\Validator\TemplateValidator
        arguments:
            - "@doctrine"
            - "@campaignchain.core.activity"