# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    campaignchain.campaign.template.hook:
        class: CampaignChain\Campaign\TemplateBundle\EntityService\HookService
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.campaign.template.copy:
        class: CampaignChain\Campaign\TemplateBundle\EntityService\CopyService
        arguments: [ @doctrine.orm.entity_manager, @service_container ]