# This file is part of the CampaignChain package.
#
# (c) Sandro Groganz <sandro@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    campaignchain.campaign.campaign_template.twig.campaignchain_campaign_template_extension:
        class: CampaignChain\Campaign\TemplateBundle\Twig\CampaignChainCampaignTemplateExtension
        arguments: [@doctrine.orm.entity_manager, "@service_container"]
        tags:
            - { name: twig.extension }
